### ISSUE TITLE
Configure INITIAL_WINDOW_SIZE for gRPC

### ISSUE THREAD

**Issue by Scottmitch** [apple/servicetalk#1121]
The default INITIAL_WINDOW_SIZE for h2 is 65535, which is relatively conservative and can negatively impact throughput.

grpc-java uses INITIAL_WINDOW_SIZE = 1MiB

We should configure it as 1MiB for st-grpc by default and consider exposing this setting for users on H2ProtocolConfig.

**Comment by idelpivnitskiy** [comment]
Resolved by #2341
