### ISSUE TITLE
Display with zoom hotkey on Macbooks Pro have annoying bug

### ISSUE THREAD

**Issue by flowl** [apple/servicetalk#1253]
[X] I don't know how to report a bug to Apple and I don't signup any site to report bugs outside of GitHub.
[X] I didn't find an email address to report a bug to Apple either.

Versions: macOS Catalina:
Present in most current minor/hotfix version up to date: yes

Reference: https://apple.stackexchange.com/questions/382559/invisible-region-on-screen-blocking-cursor

Problem explanation:

An invisible region on the screen is blocking the cursor.

Workaround: No workaround available, happens occasionally on 13" and 15" Macbooks.
Can be fixed temporarily using "zoom in, zoom out (fullscreen) zoom hotkey".

I am aware this is the wrong spot to report this but I am sure you are able to forward this issue to the according departments and people.
If not, please provide me with a GitHub repo with enabled issues or an email address I can foward this bug to.

Best,
Daniel

**Comment by Scottmitch** [comment]
Hello @flowl. Thanks for reaching out, and we can help redirect you. There are a few ways you can file a bug report and provide feedback for macOS:
1. [Feedback Assistant](https://developer.apple.com/bug-reporting/)
2. [General Feedback](https://www.apple.com/feedback/)

Option (1) does require an account (iCloud IIRC) but gives you enhanced traceability and allows for richer input(s) to help Apple triage/fix any underlying issues. Option (2) doesn't require an account (you can supply an email with your report), but may not provide the same level of visibility and ability to provide rich inputs (screen shots, core dumps, etc.).

For the best results I recommend you filing the issue directly so if there is additional feedback/validation required the folks triaging the issue can reach out, and you can get notified of any resolution.
