### ISSUE TITLE
BufferInputStream should support mark/reset

### ISSUE THREAD

**Issue by idelpivnitskiy** [apple/servicetalk#1562]
`BufferInputStream` does not implement mark/reset methods of the `InputStream`, while we can. We should implement it to make it close to `ByteArrayInputStream` and `ByteBufInputStream` (from netty) behavior.

**Comment by SivaTharun** [comment]
@idelpivnitskiy can i work on this issue, i see that the class `src/main/java/io/servicetalk/buffer/api/BufferInputStream.java`, has to implement mar and reset methods. can you also add the expectation of the method implementation, what should it essentially do.

**Comment by idelpivnitskiy** [comment]
Thank you for the interest @SivaTharun!
Absolutely, you can take it.
The goal is to implement the standard behavior of `mark/reset` methods defined by Java community in [InputStream javadoc](https://github.com/openjdk/jdk/blob/79b39445f6fcd005744c5de89ba2cd2ed5bc0a54/src/java.base/share/classes/java/io/InputStream.java#L649-L750). You can refer to [java.io.ByteArrayInputStream](https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/io/ByteArrayInputStream.java) and [io.netty.buffer.ByteBufInputStream](https://github.com/netty/netty/blob/4.1/buffer/src/main/java/io/netty/buffer/ByteBufInputStream.java) to get the basic idea of the implementation.
Please, also add tests to verify new behavior.
