### ISSUE TITLE
Jackson ByteBufferFeeder support

### ISSUE THREAD

**Issue by Scottmitch** [apple/servicetalk#1711]
Jackson currently does not provide any implementations for `ByteBufferFeeder` https://github.com/FasterXML/jackson-core/issues/478. When it does we need to revisit how to use the Jackson APIs to prefer a `ByteBufferFeeder`. The factory methods do not support a way to specify which feeder type to create.

**Comment by daschl** [comment]
Closing this ticket, see the reasoning in the commit msg of https://github.com/apple/servicetalk/commit/f3636fbdaf4b9885574530ac169e0e04f37d1622
