### ISSUE TITLE
Consolidate duplicate MathUtil

### ISSUE THREAD

**Issue by Scottmitch** [apple/servicetalk#189]
http-api and opentracing both have a duplicate `MathUtil` file. We should share code between these two modules via an `internal` module.

**Comment by heowc** [comment]
I am interested in this issue. :smile:

But do we have to create a new internal module? There is no common module in the architecture. :joy:

**Comment by NiteshKant** [comment]
@heowc its awesome that you want to contribute!
Yes there is no common module between the two modules ATM and we should create one as part of this issue. 
I would suggest creating a new module `servicetalk-utils-internal` module and have the `MathUtil` in that module. 
Do you want to explore how to create a new module? Feel free to ping here if you face issues or have questions!

**Comment by heowc** [comment]
I will send a PR with reference to other modules. 
I hope you have much feedback. Thanks you! 😄
