### ISSUE TITLE
Consider bounded exponential retry for DefaultDNSServiceDiscoverer

### ISSUE THREAD

**Issue by lewisd32** [apple/servicetalk#290]
The negative of the existing constant backoff approach is that it is pessimistic for initial retries. Maybe there is a middle ground where we write our own strategy of starting over after `n` retries. IOW, we start small, eg: 500 millis, grow exponentially till 10 retries and then start over at 500 millis. Alternatively we can simply cap the maximum retry delay.

(original discussion https://github.com/servicetalk/servicetalk/pull/283#discussion_r254420273)

Either approach makes it desirable to be able to specify a custom delay calculation in `RetryStrategies.retryWith*` methods. We may add a new signature:
```Java
public static BiIntFunction<Throwable, Completable> retryWithBackoff(
        final int maxRetries,
        final Predicate<Throwable> causeFilter,
        final Function<Integer, Long> delayFunction,
        final Executor timerExecutor) {
```
and have this used by the existing `retryWith*` methods.

**Comment by Scottmitch** [comment]
This issue is no longer relevant. We currently fail open and allow the retry to be applied externally on the Publisher
