### ISSUE TITLE
Bare CR improperly allowed in HTTP/1.1 header values

### ISSUE THREAD

**Issue by kenballus** [apple/servicetalk#3022]
# The bug

ServiceTalk allows bare CR within HTTP/1.1 header values. This is disallowed by the RFCs.

RFC 9110:
> Field values containing CR, LF, or NUL characters are invalid and dangerous, due to the varying ways that implementations might parse and interpret those characters; a recipient of CR, LF, or NUL within a field value MUST either reject the message or replace each of those characters with SP before further processing or forwarding of that message.

RFC 9112:
> A sender MUST NOT generate a bare CR (a CR character not immediately followed by LF) within any protocol elements other than the content. A recipient of such a bare CR MUST consider that element to be invalid or replace each bare CR with SP before processing the element or forwarding the message.

ServiceTalk doesn't enforce this rule.

# To reproduce

1. Start a ServiceTalk-based HTTP/1.1 server that echos back the parsed components of the request, such as [this one](https://github.com/narfindustries/http-garden/blob/main/images/servicetalk/GardenServer.java).
2. Send it a request with a bare CR in a header value, and extract the interpreted header value from the response:
```sh
printf 'GET / HTTP/1.1\r\nTest: a\ra\r\n\r\n' \
    | nc localhost 80 \
    | grep '"headers"' \
    | jq '.["headers"][0][1]' \
    | sed 's/"//g' \
    | base64 -d \
    | xxd
```
3. Observe that the CR made it into the header value:
```
00000000: 610d 61                                  a.a
```

# What other HTTP implementations do

Reject the request with a 400:
- AIOHTTP                                                                                     - Apache httpd
- FastHTTP
- Go net/http
- H2O
- HAProxy
- Hyper
- Hypercorn
- Jetty
- Libevent
- Lighttpd
- Nginx
- Node.js
- Passenger
- Puma
- Tomcat
- Unicorn
- Uvicorn
- Waitress
- WEBrick

Close the connection without responding:
- Mongoose
- Netty

Translate the CR to a space:
- Libsoup
- Twisted
- LiteSpeed

Let it through (i.e., have the same bug as ServiceTalk):
- Cheroot
- Gunicorn
- Tornado
- OpenWrt uhttpd
- OpenBSD httpd

# Platform
```
Linux 399194a6dcd8 6.9.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 05 Jul 2024 22:11:24 +0000 x86_64 GNU/Linux
```
ServiceTalk main @ 8ae9e7bec4cff5a32fe6374c5b7d531507f2cbbe

**Comment by idelpivnitskiy** [comment]
Hi @kenballus,

Thanks for reporting!

We have header value validation feature, but it's disabled by default. Some of our users enable it, when it matters. Could you please configure http-garden with validation and rerun your test? Here is what you need to do based on `BlockingHelloWorldServer` example:

```patch
Index: servicetalk-examples/http/helloworld/src/main/java/io/servicetalk/examples/http/helloworld/blocking/BlockingHelloWorldServer.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/servicetalk-examples/http/helloworld/src/main/java/io/servicetalk/examples/http/helloworld/blocking/BlockingHelloWorldServer.java b/servicetalk-examples/http/helloworld/src/main/java/io/servicetalk/examples/http/helloworld/blocking/BlockingHelloWorldServer.java
--- a/servicetalk-examples/http/helloworld/src/main/java/io/servicetalk/examples/http/helloworld/blocking/BlockingHelloWorldServer.java	(revision 8ae9e7bec4cff5a32fe6374c5b7d531507f2cbbe)
+++ b/servicetalk-examples/http/helloworld/src/main/java/io/servicetalk/examples/http/helloworld/blocking/BlockingHelloWorldServer.java	(date 1722365749494)
@@ -15,6 +15,8 @@
  */
 package io.servicetalk.examples.http.helloworld.blocking;
 
+import io.servicetalk.http.api.DefaultHttpHeadersFactory;
+import io.servicetalk.http.netty.HttpProtocolConfigs;
 import io.servicetalk.http.netty.HttpServers;
 
 import static io.servicetalk.http.api.HttpSerializers.textSerializerUtf8;
@@ -23,6 +25,7 @@
 
     public static void main(String[] args) throws Exception {
         HttpServers.forPort(8080)
+                .protocols(HttpProtocolConfigs.h1().headersFactory(new DefaultHttpHeadersFactory(true, true, true)).build())
                 .listenBlockingAndAwait((ctx, request, responseFactory) ->
                         responseFactory.ok().payloadBody("Hello World!", textSerializerUtf8()))
                 .awaitShutdown();
```

**Comment by kenballus** [comment]
Thanks! Have now updated, and can confirm that this fixes the issue.
