### ISSUE TITLE
TcpTransportObserverErrorsTest failure

### ISSUE THREAD

**Issue by Scottmitch** [apple/servicetalk#3060]
https://github.com/apple/servicetalk/actions/runs/10944459471/job/30387127322?pr=3059#step:8:1584

```
> Task :servicetalk-tcp-netty-internal:test

TcpTransportObserverErrorsTest > testConnectionClosed(ErrorSource) > [1] CONNECTION_REFUSED FAILED
    java.util.concurrent.TimeoutException: testConnectionClosed(io.servicetalk.tcp.netty.internal.TcpTransportObserverErrorsTest$ErrorSource) timed out after 30 seconds
```

**Comment by Scottmitch** [comment]
https://github.com/apple/servicetalk/actions/runs/10959243976/job/30445152690?pr=3061#step:8:1518

```
TcpTransportObserverErrorsTest > testConnectionClosed(ErrorSource) > [1] CONNECTION_REFUSED FAILED
    java.util.concurrent.TimeoutException: testConnectionClosed(io.servicetalk.tcp.netty.internal.TcpTransportObserverErrorsTest$ErrorSource) timed out after 30 seconds
```

**Comment by bryce-anderson** [comment]
It looks like this is failing to verify one of the mock calls, specifically the `verify(clientConnectionObserver, await()).connectionClosed(exceptionCaptor.capture());` The `connectionClosed(Throwable)` isn't being called, instead it's the no-argument overload of that method [here](https://github.com/apple/servicetalk/blob/main/servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/ConnectionObserverInitializer.java#L94).

**Comment by bryce-anderson** [comment]
There appears to be some non-determinism between when we set the reason the channel was closed via `ChannelCloseUtils.assignConnectionError` and when we read it back out via `ChannelCloseUtils.channelError`.

**Comment by bryce-anderson** [comment]
What is likely happening is a race between which listener gets added first to the connect future: the one added by netty in the bootstrap (CLOSE_ON_FAILURE) and our own that we add in the `TcpConnector.connect -> handleSubscribe` method. We might be able to add our listener before we call the netty `.connect(..)` method, therefore removing the race.
