### ISSUE TITLE
ConcurrentRequestsHttpConnectionFilter should leverage NettyConnection.onClosing() instead of ConnectionContext.onClose()

### ISSUE THREAD

**Issue by jayv** [apple/servicetalk#309]
We used to set `maxPipelinedRequests = 0` from `NettyConnection.onClosing()` which lead to misleading error messages. With the improved API on `RequestConcurrencyController` to indicate `RejectedPermanently`, we can minimize unnecessary failed requests on connection closure by triggering `RejectedPermanently` from `NettyConnection.onClosing()` however it’s not exposed.

`AbstractStreamingHttpConnection` has been modified to work around the shortcoming that `ConcurrentRequestsHttpConnectionFilter` has no access to `onClosing()`, once we make it available on `NettyConnectionContext` we must also update `AbstractStreamingHttpConnection` to leverage `onClosing()` again.

**Comment by idelpivnitskiy** [comment]
`ConcurrentRequestsHttpConnectionFilter` was removed in #948.
