### ISSUE TITLE
RedirectingClientAndConnectionFilterTest should leverage AbstractHttpRequesterFilterTest 

### ISSUE THREAD

**Issue by jayv** [apple/servicetalk#396]
As part of https://github.com/servicetalk/servicetalk/pull/395 I noticed that `RedirectingClientAndConnectionFilterTest`  could probably leverage the `AbstractHttpRequesterFilterTest` test tooling, it seems its approach is closely related to the one in `RedirectingClientAndConnectionFilterTest` and can reuse most of the code.

**Comment by volyx** [comment]
I will take this issue :)

**Comment by idelpivnitskiy** [comment]
This issue was resolved in #867
