### ISSUE TITLE
HTTP/1.x Support Expect/Continue

### ISSUE THREAD

**Issue by Scottmitch** [apple/servicetalk#536]
Currently we don't account for the Expect/Continue request/response life cycle. This may introduce "interim responses" on the client side, which we may forward to users instead of the "real response". We can consider handling this in a phases:

1. minimal approach - client discards 1xx "interim responses", server doesn't support sending 1xx responses.
2. sophisticated way - if client sends 100-continue we delay sending the payload until we get the 100-continue response for some amount of time, if the server sees an `expect: continue` header, and the user consumes the request content we send a 100-continue response.

The minimal approach may be "good enough" to be RFC compliant (investigation is required for proxy use case on the server).

Related discussion:
https://github.com/servicetalk/servicetalk/pull/529#discussion_r279598154

**Comment by idelpivnitskiy** [comment]
Resolved by #2037
