### ISSUE TITLE
DefaultMultiAddressHttpClientBuilder doesn't offer a way to configure the builder per ResolvedAddress

### ISSUE THREAD

**Issue by Scottmitch** [apple/servicetalk#543]
`DefaultMultiAddressHttpClientBuilder` currently adds special cases for `SslConfigProvider` and the "host header transformer" to modify the configuration for each resolved address. However the user may want to modify other characteristics for each address. If we could expose the "single address builder" (or something similar) so the user can configure all the parameters we wouldn't need the special case configuration options on the `DefaultMultiAddressHttpClientBuilder`.

This will also allow the user to configure items that don't make as much sense at the `DefaultMultiAddressHttpClientBuilder` (e.g. h2 prior knowledge).

Related:
https://github.com/servicetalk/servicetalk/pull/529#discussion_r279944465

**Comment by idelpivnitskiy** [comment]
This is provided via `MultiAddressHttpClientBuilder.initializer(SingleAddressInitializer)` now, can not find the exact PR that added this feature.
