### ISSUE TITLE
Support building on windows

### ISSUE THREAD

**Issue by idelpivnitskiy** [apple/servicetalk#575]
Attempt to build on Windows with both OpenJDK 8 and 11 produces 9 errors:

- 7 due to Checkstyle crashes (`Unable to create Root Module`),
- 1 due to failure to load test PEM files,
- 1 due to some weird file system permission issue when writing jUnit result.

To be able to build on Windows and add `gradlew.bat` scripts more investigation of the root causes for these issues required.

**Comment by shekhar-rajak** [comment]
Hi,

We can also use github actions where workflow can be setup for windows machine as well. Refer: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idruns-on

**Comment by NiteshKant** [comment]
@shekhar-rajak thanks for pointing to that detail.

This issue is to make sure that the project builds on windows, once that is done we can figure out how to setup CI (current jenkins or github actions) to do this.
