### ISSUE TITLE
DefaultHttpHeaders does not hold http header properly.

### ISSUE THREAD

**Issue by mike-neck** [apple/servicetalk#854]
`DefaultHttpHeaders` does not hold http header values as client send.  The http header value from `DefaultHttpHeaders#get(String)` is missing the first character.

---

### servicetalk version

0.19.0

### output of `uname -a`

```
 uname -a
Darwin mike-neck.local 19.0.0 Darwin Kernel Version 19.0.0: Wed Sep 25 20:18:50 PDT 2019; root:xnu-6153.11.26~2/RELEASE_X86_64 x86_64
```

### output of `java -version`

```
$ java -version
Picked up _JAVA_OPTIONS: -Dfile.encoding=UTF-8
openjdk version "1.8.0_202"
OpenJDK Runtime Environment (Zulu 8.36.0.1-CA-macosx) (build 1.8.0_202-b05)
OpenJDK 64-Bit Server VM (Zulu 8.36.0.1-CA-macosx) (build 25.202-b05, mixed mode)
```

### context

* to retrieve http header value

---

Reproduction code
---

### server

```groovy
@GrabResolver(name = 'servicetalk', root='https://dl.bintray.com/servicetalk/servicetalk/')
@Grab("io.servicetalk:servicetalk-http-netty:0.19.0")
@Grab("io.servicetalk:servicetalk-annotations:0.19.0")
@Grab('org.slf4j:slf4j-simple:1.7.29')

import io.servicetalk.concurrent.api.Single
import io.servicetalk.http.api.*
import io.servicetalk.http.netty.HttpServers

import java.util.concurrent.*

import static io.servicetalk.http.api.HttpSerializationProviders.textSerializer


HttpServers.forPort(8000)
    .listenAndAwait([handle: {HttpServiceContext ctx, HttpRequest req, HttpResponseFactory factory ->
        def myHeader = req.headers().get('MY')
        Single.succeeded(factory.ok().payloadBody("${myHeader}" as String, textSerializer()))
    }] as HttpService).awaitShutdown()
```

(groovy code)

### client

```
curl -i http://localhost:8000 -H 'MY:foo-bar'
```

This client expects to receive response as ...

```
HTTP/1.1 200 OK
content-length: 6
content-type: text/plain; charset=UTF-8

foo-bar
```

But it will receive as bellow.

```
HTTP/1.1 200 OK
content-length: 6
content-type: text/plain; charset=UTF-8

oo-bar
```

**Comment by NiteshKant** [comment]
@mike-neck yes this seems like a bug. As per the spec[1] the whitespace between the `:` and header value is optional but we consider it as required[2] hence skip a character after the `:`. As the request header does not contain a space, while fetching the header, the first character in the value is skipped. Here is what is sent on the wire from `curl`:

```
➜  servicetalk git:(master) ✗ curl -vi http://localhost:8080 -H 'FOO:foo-bar'
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.64.1
> Accept: */*
> FOO:foo-bar
```

[1] https://tools.ietf.org/html/rfc7230#section-3.2
[2] `header-field   = field-name ":" OWS field-value OWS`

**Comment by Scottmitch** [comment]
@mike-neck - issue has been fixed by @idelpivnitskiy, should be available in snapshot and we will generate a release soon. Thanks for reporting!

**Comment by jayv** [comment]
Fix released as part of https://github.com/apple/servicetalk/releases/tag/0.20.0
