### ISSUE TITLE
Add missed HttpResponseStatus constants

### ISSUE THREAD

**Issue by idelpivnitskiy** [apple/servicetalk#871]
`io.servicetalk.http.api.HttpResponseStatus` class contains constant values for different status codes. We should revisit this list and add standardized (official) statuses that are currently missed. This two lists will be helpful:
1. IANA HTTP Status Codes: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
2. Wikipedia List of HTTP Status Codes: https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

**Comment by volyx** [comment]
I would take it
