### ISSUE TITLE
Add RFC links for standardised HttpHeaderNames constants

### ISSUE THREAD

**Issue by idelpivnitskiy** [apple/servicetalk#885]
We would like to enhance javadoc for HTTP header name constants in `HttpHeaderNames` class with links to the related RFC sections.

An example of the expected result for the [`host` header](https://github.com/apple/servicetalk/blob/b4413a126f5718b30ec4877cbc057c2599f543dc/servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpHeaderNames.java#L186):
```
    /**
     * {@code "host"}
     *
     * @see <a href="https://tools.ietf.org/html/rfc7230#section-5.4">RFC7230, section 5.4</a>
     */
```

Non-standardized but widely used headers, like `X-Forwarded-For` may be without a link to RFC.

**Comment by karim-elngr** [comment]
Going through [iana message-headers assignments](https://www.iana.org/assignments/message-headers/message-headers.xhtml)
- `Content-Base` was introduced by [RFC2068 section 14.11](https://tools.ietf.org/html/rfc2068#section-14.11) and obsoleted by [RFC2616 section 19.6.3](https://tools.ietf.org/html/rfc2616#section-19.6.3) 

> Content-Base was deleted from the specification: it was not
   implemented widely, and there is no simple, safe way to introduce it
   without a robust extension mechanism. In addition, it is used in a
   similar, but not identical fashion in MHTML [45].

**Comment by idelpivnitskiy** [comment]
If it was removed in 1999 I'm ok to remove this header name from our constants as a separate PR before or after a PR for this issue. Even if someone will request it with a clear justification, we can add this header constant later. For now, better to minimize unnecessary public API. Thanks for the catch @karim-elngr

**Comment by shekhar-rajak** [comment]
Hi,

I am trying to understand the ServiceTalk codebase, so that I can contribute to it. For this issue I understand that we need to update in [this file](https://github.com/apple/servicetalk/blob/master/servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpHeaderNames.java) - [doc file](https://apple.github.io/servicetalk/servicetalk/SNAPSHOT/javadoc/index.html). So should we add the `RFC7230, section 5.4` or the latest one in each field [after `@code`](https://github.com/apple/servicetalk/blob/master/servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpHeaderNames.java#L26) ?

**Comment by idelpivnitskiy** [comment]
Thanks for the interest @shekhar-rajak!
Right, for each existing javadoc comment in [HttpHeaderNames](https://github.com/apple/servicetalk/blob/master/servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpHeaderNames.java) file we would like to add a `@see` tag with the link to the related RFC section. It's ok not to add any link if there is no standardized RFC for some header names, like `X-Forwarded-For`.

**Comment by shekhar-rajak** [comment]
Thanks @idelpivnitskiy I will work on it.

**Comment by shekhar-rajak** [comment]
@idelpivnitskiy , Can we use any RFC link? 

Like `content-encoding` is present at https://tools.ietf.org/html/rfc7231#section-3.1.2.2 but it is not present in https://tools.ietf.org/html/rfc7230

So should we use 

```
    /**
     * {@code "content-encoding"}
     *
     * @see <a href="https://tools.ietf.org/html/rfc7231#section-3.1.2.2">RFC7231, section 3.1.2.2</a>
     */
    public static final CharSequence CONTENT_ENCODING = newAsciiString("content-encoding");

```

or should we leave it?

**Comment by idelpivnitskiy** [comment]
Sure, this is 💯 fine. Some headers are defined in difference RFCs. Moreover, in 2014 the HTTP/1.1 was split into 6 different RFC documents: https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol#History

You can use IANA's [Message Headers](https://www.iana.org/assignments/message-headers/message-headers.xhtml) list to get an idea about references for the header names.

**Comment by shekhar-rajak** [comment]
Thanks @idelpivnitskiy! These link are helpful.
