### ISSUE TITLE
Eliminate duplication in `http-api` HttpDeserializers

### ISSUE THREAD

**Issue by karim-elngr** [apple/servicetalk#886]
Currently there is duplication in `checkContentType` in the following classes:

https://github.com/apple/servicetalk/blob/4b2b4d503eb07b1865eb1516c5bc49f8e55da443/servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultClassHttpDeserializer.java#L66-L71

https://github.com/apple/servicetalk/blob/4b2b4d503eb07b1865eb1516c5bc49f8e55da443/servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultTypeHttpDeserializer.java#L67-L72

https://github.com/apple/servicetalk/blob/4b2b4d503eb07b1865eb1516c5bc49f8e55da443/servicetalk-http-api/src/main/java/io/servicetalk/http/api/FormUrlEncodedHttpDeserializer.java#L102-L107

https://github.com/apple/servicetalk/blob/4b2b4d503eb07b1865eb1516c5bc49f8e55da443/servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpStringDeserializer.java#L101-L106

We can eliminate this code duplication by extracting `checkContentType` to `HeaderUtils` and providing a general `checkContentType` : 
``` 
static void checkContentType(final HttpHeaders headers, 
                              Predicate<HttpHeaders> checkContentType) {
    if (!checkContentType.test(headers)) {
        throw new SerializationException("Unexpected headers, can not deserialize. Headers: "
            + headers.toString(DEFAULT_DEBUG_HEADER_FILTER));
    }
}
```
and replacing each call to `checkContentType(headers);` with `checkContentType(headers, checkContentType);`

Related issues: #878

**Comment by idelpivnitskiy** [comment]
SGTM!
@karim-elngr are you interested in submitting a PR?

**Comment by karim-elngr** [comment]
@idelpivnitskiy Yes, will do so.
