### ISSUE TITLE
Generated gRPC RPC interfaces should be annotated as `@FunctionalInterface`

### ISSUE THREAD

**Issue by NiteshKant** [apple/servicetalk#908]
For each method in the gRPC service definition we generate a separate `[Blocking][methodName]Rpc` interface which has one method corresponding to the name of the RPC method. These interfaces should be marked as `@FunctionalInterface` as we do not expect them to have more than one non-default method.

eg: for [route guide example](https://github.com/apple/servicetalk/blob/b936679d65d2ea5366cb2750e0212aa52a09dc30/servicetalk-examples/grpc/routeguide/src/main/proto/route_guide.proto#L24) we generate 8 interfaces:

- `GetFeatureRpc`
- `BlockingGetFeatureRpc`
- `ListFeaturesRpc`
- `BlockingListFeaturesRpc`
- `RecordRouteRpc`
- `BlockingRecordRouteRpc`
- `RouteChatRpc`
- `BlockingRouteChatRpc`

All these interfaces should be marked as `@FunctionalInterface`.

This requires changes to gRPC [`Generator`](https://github.com/apple/servicetalk/blob/master/servicetalk-grpc-protoc/src/main/java/io/servicetalk/grpc/protoc/Generator.java). For reference, these interfaces are generated as part of the method `addServiceRpcInterfaces()`:

https://github.com/apple/servicetalk/blob/master/servicetalk-grpc-protoc/src/main/java/io/servicetalk/grpc/protoc/Generator.java#L248-L269

**Comment by volyx** [comment]
I will take this one
