### ISSUE TITLE
Add missed `when*` operators for async sources

### ISSUE THREAD

**Issue by idelpivnitskiy** [apple/servicetalk#926]
All asynchronous sources (`Completable`, `Single`, `Publisher`) have `before*`, `when*`, and `after*` operators, for example:
- `Completable.beforeOnError(...)`
- `Completable.whenOnError(...)`
- `Completable.afterOnError(...)`

However, a few `when*` operators were missed:
- `Completable.whenOnSubscribe(Consumer<Cancellable>)`
- `Completable.whenSubscriber(Supplier<? extends Subscriber>)`
- `Single.whenOnSubscribe(Consumer<Cancellable>)`
- `Single.whenSubscriber(Supplier<? extends Subscriber<? super T>>)`
- `Publisher.whenSubscription(Supplier<? extends Subscription>)`
- `Publisher.whenSubscriber(Supplier<? extends Subscriber<? super T>>)`

We should add these operators. `when*` usually behaves like `after*`.

**Comment by shekhar-rajak** [comment]
Hi,

I want to work on this. Should we have `whenOnSubscribe` method like this [`Publisher. whenOnSubscribe`](https://github.com/apple/servicetalk/blob/master/servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java#L577) for `Completable.whenOnSubscribe `, `Single.whenOnSubscribe ` ?

**Comment by idelpivnitskiy** [comment]
Thanks for your interest @shekhar-rajak!
Right, these two and all other operators from the issue description are missed and should be added.

**Comment by shekhar-rajak** [comment]
Thanks, @idelpivnitskiy I will work on it. Please let me know how can I verify/test/debug the method newly created.

**Comment by idelpivnitskiy** [comment]
Since this work does not add new logic (it only makes API consistent) and all new methods will delegate to the already existing `after*` methods, I don't think we need special tests here. See, `Completable.whenOnError(...)` as an example:
https://github.com/apple/servicetalk/blob/b4413a126f5718b30ec4877cbc057c2599f543dc/servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Completable.java#L175-L177

**Comment by shekhar-rajak** [comment]
> Since this work does not add new logic (it only makes API consistent) and all new methods will delegate to the already existing `after*` methods, I don't think we need special tests here. See, `Completable.whenOnError(...)` as an example:
> https://github.com/apple/servicetalk/blob/b4413a126f5718b30ec4877cbc057c2599f543dc/servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Completable.java#L175-L177

Thanks,  I understand it.
